### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Sayak9495** [The-Club/Cube-Info#1]
The Cube needs a online portal where other users and members can find the right content.

**Comment by troymusician** [comment]
What are the things to be included in the website??

**Comment by troymusician** [comment]
https://www.skynova.com/editWebsite.php
check this website out

**Comment by troymusician** [comment]
http://srmramapuramthecube.skynova.io/
check this out??.....

**Comment by troymusician** [comment]
http://srmrmpthecube.skynova.io/
Check this site......Tell me what more should I add in it...
And if any changes required tell me
