### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by Sayak9495** [The-Club/Cube-Info#3]
We would be needing an IRC Channel as well a IRC bot. So that everybody who is interested can contact the members as well as Core-Members of The Cube.

**Comment by troymusician** [comment]
IRC channel is created.
current user name :- troymusician
current channel :- #dgplug

**Comment by curiousrohan** [comment]
IRC Channel and IRC user are different things. You just created a IRC username. We need separate a separate channel for our club.  Something​ like #thecube . Also we need a IRC bot to monitor activities.

**Comment by Sayak9495** [comment]
@troymusician will create a IRC Channel. And after that, @curiousrohan you take care of the bot.

**Comment by curiousrohan** [comment]
We need to finalize a club name asap before creating IRC Channel.

**Comment by Sayak9495** [comment]
IRC channel has been created with the Channel name #dcube 
And @curiousrohan will take over the work for BatulBot for IRC channel.

**Comment by curiousrohan** [comment]
#4 Closing this issue and opening a separate issue for IRC Bot.
